version: '3.9'

services:
  # Serwisy backendowe
  userservice:
    build:
      context: ./backend/userService
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/musify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Dudzio1423

  productservice:
    build:
      context: ./backend/productService
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/musify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Dudzio1423
    volumes:
      - ./backend/uploads/products:/uploads/products

  orderservice:
    build:
      context: ./backend/orderService
    ports:
      - "8083:8083"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/musify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Dudzio1423
      NOTIFICATION_SERVICE_URI: http://notificationservice:8085 # Dodano URI do NotificationService

  reviewservice:
    build:
      context: ./backend/reviewService
    ports:
      - "8084:8084"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/musify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Dudzio1423

  notificationservice:
    build:
      context: ./backend/notificationService
    ports:
      - "8085:8085"
    networks:
      - app-network
    environment:
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: your-email@gmail.com
      SPRING_MAIL_PASSWORD: your-email-password
      SPRING_MAIL_PROTOCOL: smtp
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true

  api_gateway:
    build:
      context: ./backend/api_gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      PRODUCT_SERVICE_URI: http://productservice:8082
      USER_SERVICE_URI: http://userservice:8081
      ORDER_SERVICE_URI: http://orderservice:8083
      REVIEW_SERVICE_URI: http://reviewservice:8084
      NOTIFICATION_SERVICE_URI: http://notificationservice:8085 # Dodano URI do NotificationService
    depends_on:
      - userservice
      - productservice
      - orderservice
      - reviewservice
      - notificationservice

  # Baza danych PostgreSQL
  database:
    image: postgres:13
    container_name: musify-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dudzio1423
      POSTGRES_DB: musify
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Frontend będzie dostępny pod localhost:3000
    networks:
      - app-network
    depends_on:
      - api_gateway

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
